version: '3.5'

services:
  cli:
    image: paliari/apache-php8:2.1.0-dev
    command: bash
    user: '1000:1000'
    volumes:
      - .:/var/www/html
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/.gitconfig
