version: '3.5'

services:
  cli:
    image: paliari/apache-php8-oci8:1.3.0-dev
    command: bash
    user: '1000:1000'
    volumes:
      - .:/var/www/html
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/.gitconfig
